// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe0wyM1xa2nwjgdaMRjj1hXFd4VGcRk_k',
    appId: '1:1096041236240:web:8367dd937f04b2a6018795',
    messagingSenderId: '1096041236240',
    projectId: 'my-cse-b5ddf',
    authDomain: 'my-cse-b5ddf.firebaseapp.com',
    storageBucket: 'my-cse-b5ddf.firebasestorage.app',
    measurementId: 'G-S1VP2RYHTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTO7cSAFKF_YnMFTsigoIR0vnLgz3SCLg',
    appId: '1:1096041236240:android:0c63e9d977575998018795',
    messagingSenderId: '1096041236240',
    projectId: 'my-cse-b5ddf',
    storageBucket: 'my-cse-b5ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0mZmEb-rKtOaQE1agRDeUw1nuyTjS2NY',
    appId: '1:1096041236240:ios:077e2a57edae3f46018795',
    messagingSenderId: '1096041236240',
    projectId: 'my-cse-b5ddf',
    storageBucket: 'my-cse-b5ddf.firebasestorage.app',
    iosBundleId: 'com.example.csApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0mZmEb-rKtOaQE1agRDeUw1nuyTjS2NY',
    appId: '1:1096041236240:ios:077e2a57edae3f46018795',
    messagingSenderId: '1096041236240',
    projectId: 'my-cse-b5ddf',
    storageBucket: 'my-cse-b5ddf.firebasestorage.app',
    iosBundleId: 'com.example.csApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe0wyM1xa2nwjgdaMRjj1hXFd4VGcRk_k',
    appId: '1:1096041236240:web:fce3c1b4b7492a46018795',
    messagingSenderId: '1096041236240',
    projectId: 'my-cse-b5ddf',
    authDomain: 'my-cse-b5ddf.firebaseapp.com',
    storageBucket: 'my-cse-b5ddf.firebasestorage.app',
    measurementId: 'G-SVMFWDJP51',
  );

}